matrix:
  include:
    - os: linux
      sudo: required
    - os: osx
      osx_image: xcode7.3

language: node_js

node_js:
  - '6'

compiler: clang

addons:
  apt:
    packages:
    - build-essential

install:
- npm install

script:
- npm test
