matrix:
  include:
    - os: linux
      sudo: required
      node_js: '6'
      env: CC=clang CXX=clang++ npm_config_clang=1
      compiler: clang

    - os: osx
      osx_image: xcode7.3
      node_js: '6'

language: node_js

compiler: clang

addons:
  apt:
    sources:
    - build-essential

install:
- npm install

script:
- npm test
