matrix:
  include:
    - os: linux
      sudo: required
      node_js: '6'
      env: CXX=g++-4.8

    - os: osx
      osx_image: xcode7.3
      node_js: '6'

language: node_js

compiler: clang

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

install:
- npm install

script:
- npm run lint
- npm test
